export const GLOBAL_SET_TOAST = 'GLOBAL/SET_TOAST'
export const GLOBAL_UNSET_TOAST = 'GLOBAL/UNSET_TOAST'

export const DASHBOARD_FETCH_START = 'DASHBOARD/FETCH_START'
export const DASHBOARD_FETCH_ERROR = 'DASHBOARD/FETCH_ERROR'
export const DASHBOARD_FETCH_SUCCESS = 'DASHBOARD/FETCH_SUCCESS'

export const SUBMIT_LINK_START = 'DASHBOARD/SUBMIT_START'
export const SUBMIT_LINK_ERROR = 'DASHBOARD/SUBMIT_ERROR'
export const SUBMIT_LINK_SUCCESS = 'DASHBOARD/SUBMIT_SUCCESS'
export const SUBMIT_LINK_ERROR_HOST = 'DASHBOARD/SUBMIT_ERROR_HOST'

export const ADD_HOST_START = 'DASHBOARD/ADD_HOST_START'
export const ADD_HOST_ERROR = 'DASHBOARD/ADD_HOST_ERROR'
export const ADD_HOST_SUCCESS = 'DASHBOARD/ADD_HOST_SUCCESS'

export const FILTER_START = 'DASHBOARD/FILTER_START'
export const FILTER_ERROR = 'DASHBOARD/FILTER_ERROR'
export const FILTER_SUCCESS = 'DASHBOARD/FILTER_SUCCESS'

export const DELETE_URL_START = 'DASHBOARD/DELETE_START'
export const DELETE_URL_ERROR = 'DASHBOARD/DELETE_ERROR'
export const DELETE_URL_SUCCESS = 'DASHBOARD/DELETE_SUCCESS'

export const SHORT_LINK_CLICK = 'DASHBOARD/SHORT_LINK_CLICK'
export const SHORT_LINK_COPY = 'DASHBOARD/SHORT_LINK_COPY'

export const DETAIL_FETCH_START = 'DETAIL/FETCH_START'
export const DETAIL_FETCH_ERROR = 'DETAIL/FETCH_ERROR'
export const DETAIL_FETCH_SUCCESS = 'DETAIL/FETCH_SUCCESS'

export const LOGIN_START = 'LOGIN/START'
export const LOGIN_ERROR = 'LOGIN/ERROR'
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS'

export const REFRESH_TOKEN_START = 'AUTH/REFRESH_TOKEN_START'
export const REFRESH_TOKEN_SUCCESS = 'AUTH/REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_ERROR = 'AUTH/REFRESH_TOKEN_ERROR'

export const USER_INFO_START = 'SETTINGS/USER_INFO_START'
export const USER_INFO_SUCCESS = 'SETTINGS/USER_INFO_SUCCESS'
export const USER_INFO_ERROR = 'SETTINGS/USER_INFO_ERROR'

export const API_KEY_START = 'SETTINGS/API_KEY_START'
export const API_KEY_SUCCESS = 'SETTINGS/API_KEY_SUCCESS'
export const API_KEY_ERROR = 'SETTINGS/API_KEY_ERROR'

export const REMOVE_API_KEY_START = 'SETTINGS/REMOVE_API_KEY_START'
export const REMOVE_API_KEY_SUCCESS = 'SETTINGS/REMOVE_API_KEY_SUCCESS'
export const REMOVE_API_KEY_ERROR = 'SETTINGS/REMOVE_API_KEY_ERROR'

export const ADD_API_KEY_START = 'SETTINGS/ADD_API_KEY_START'
export const ADD_API_KEY_SUCCESS = 'SETTINGS/ADD_API_KEY_SUCCESS'
export const ADD_API_KEY_ERROR = 'SETTINGS/ADD_API_KEY_ERROR'

export const CUSTOM_MD_FETCH_START = 'SETTINGS/CUSTOM_MD_FETCH_START'
export const CUSTOM_MD_FETCH_SUCCESS = 'SETTINGS/CUSTOM_MD_FETCH_SUCCESS'
export const CUSTOM_MD_FETCH_ERROR = 'SETTINGS/CUSTOM_MD_FETCH_ERROR'

export const CUSTOM_MD_SAVE_START = 'SETTINGS/CUSTOM_MD_SAVE_START'
export const CUSTOM_MD_SAVE_SUCCESS = 'SETTINGS/CUSTOM_MD_SAVE_SUCCESS'
export const CUSTOM_MD_SAVE_ERROR = 'SETTINGS/CUSTOM_MD_SAVE_ERROR'

export const USERS_FETCH_START = 'SETTINGS/USERS_FETCH_START'
export const USERS_FETCH_SUCCESS = 'SETTINGS/USERS_FETCH_SUCCESS'
export const USERS_FETCH_ERROR = 'SETTINGS/USERS_FETCH_ERROR'

export const USERS_DEACTIVATE_START = 'SETTINGS/USERS_DEACTIVATE_START'
export const USERS_DEACTIVATE_SUCCESS = 'SETTINGS/USERS_DEACTIVATE_SUCCESS'
export const USERS_DEACTIVATE_ERROR = 'SETTINGS/USERS_DEACTIVATE_ERROR'

export const USERS_ADD_START = 'SETTINGS/USERS_ADD_START'
export const USERS_ADD_SUCCESS = 'SETTINGS/USERS_ADD_SUCCESS'
export const USERS_ADD_ERROR = 'SETTINGS/USERS_ADD_ERROR'

export const VALIDATE_HASH_START = 'ACTIVATE/VALIDATE_HASH_START'
export const VALIDATE_HASH_SUCCESS = 'ACTIVATE/VALIDATE_HASH_SUCCESS'
export const VALIDATE_HASH_ERROR = 'ACTIVATE/VALIDATE_HASH_ERROR'

export const ACTIVATE_ACCOUNT_START = 'ACTIVATE/ACTIVATE_ACCOUNT_START'
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE/ACTIVATE_ACCOUNT_SUCCESS'
export const ACTIVATE_ACCOUNT_ERROR = 'ACTIVATE/ACTIVATE_ACCOUNT_ERROR'

export const SET_PASSWORD_START = 'ACTIVATE/SET_PASSWORD_START'
export const SET_PASSWORD_SUCCESS = 'ACTIVATE/SET_PASSWORD_SUCCESS'
export const SET_PASSWORD_ERROR = 'ACTIVATE/SET_PASSWORD_ERROR'

export const CUSTOM_MARKUP_START = 'ERROR_PAGE/CUSTOM_MARKUP_START'
export const CUSTOM_MARKUP_SUCCESS = 'ERROR_PAGE/CUSTOM_MARKUP_SUCCESS'
export const CUSTOM_MARKUP_ERROR = 'ERROR_PAGE/CUSTOM_MARKUP_ERROR'

export const GET_ME_START = 'USER/GET_ME_START'
export const GET_ME_SUCCESS = 'USER/GET_ME_SUCCESS'
export const GET_ME_ERROR = 'USER/GET_ME_ERROR'
