export const DASHBOARD_FETCH_START = 'DASHBOARD/FETCH_START'
export const DASHBOARD_FETCH_ERROR = 'DASHBOARD/FETCH_ERROR'
export const DASHBOARD_FETCH_SUCCESS = 'DASHBOARD/FETCH_SUCCESS'

export const SUBMIT_LINK_START = 'DASHBOARD/SUBMIT_START'
export const SUBMIT_LINK_ERROR = 'DASHBOARD/SUBMIT_ERROR'
export const SUBMIT_LINK_SUCCESS = 'DASHBOARD/SUBMIT_SUCCESS'

export const DASHBOARD_ADD_URL_START = 'DASHBOARD/ADD_URL_START'
export const DASHBOARD_ADD_URL_ERROR = 'DASHBOARD/ADD_URL_ERROR'
export const DASHBOARD_ADD_URL_SUCCESS = 'DASHBOARD/ADD_URL_SUCCESS'

export const DETAIL_FETCH_START = 'DETAIL/FETCH_START'
export const DETAIL_FETCH_ERROR = 'DETAIL/FETCH_ERROR'
export const DETAIL_FETCH_SUCCESS = 'DETAIL/FETCH_SUCCESS'

export const LOGIN_START = 'LOGIN/START'
export const LOGIN_ERROR = 'LOGIN/ERROR'
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS'
