export const GLOBAL_SET_TOAST = 'GLOBAL/SET_TOAST'
export const GLOBAL_UNSET_TOAST = 'GLOBAL/UNSET_TOAST'

export const DASHBOARD_FETCH_START = 'DASHBOARD/FETCH_START'
export const DASHBOARD_FETCH_ERROR = 'DASHBOARD/FETCH_ERROR'
export const DASHBOARD_FETCH_SUCCESS = 'DASHBOARD/FETCH_SUCCESS'

export const SUBMIT_LINK_START = 'DASHBOARD/SUBMIT_START'
export const SUBMIT_LINK_ERROR = 'DASHBOARD/SUBMIT_ERROR'
export const SUBMIT_LINK_SUCCESS = 'DASHBOARD/SUBMIT_SUCCESS'
export const SUBMIT_LINK_ERROR_HOST = 'DASHBOARD/SUBMIT_ERROR_HOST'

export const ADD_HOST_START = 'DASHBOARD/ADD_HOST_START'
export const ADD_HOST_ERROR = 'DASHBOARD/ADD_HOST_ERROR'
export const ADD_HOST_SUCCESS = 'DASHBOARD/ADD_HOST_SUCCESS'

export const FILTER_START = 'DASHBOARD/FILTER_START'
export const FILTER_ERROR = 'DASHBOARD/FILTER_ERROR'
export const FILTER_SUCCESS = 'DASHBOARD/FILTER_SUCCESS'

export const DELETE_URL_START = 'DASHBOARD/DELETE_START'
export const DELETE_URL_ERROR = 'DASHBOARD/DELETE_ERROR'
export const DELETE_URL_SUCCESS = 'DASHBOARD/DELETE_SUCCESS'

export const SHORT_LINK_CLICK = 'DASHBOARD/SHORT_LINK_CLICK'
export const SHORT_LINK_COPY = 'DASHBOARD/SHORT_LINK_COPY'

export const DETAIL_FETCH_START = 'DETAIL/FETCH_START'
export const DETAIL_FETCH_ERROR = 'DETAIL/FETCH_ERROR'
export const DETAIL_FETCH_SUCCESS = 'DETAIL/FETCH_SUCCESS'

export const LOGIN_START = 'LOGIN/START'
export const LOGIN_ERROR = 'LOGIN/ERROR'
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS'

export const REFRESH_TOKEN_START = 'AUTH/REFRESH_TOKEN_START'
export const REFRESH_TOKEN_SUCCESS = 'AUTH/REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_ERROR = 'AUTH/REFRESH_TOKEN_ERROR'
