CREATE DATABASE IF NOT EXISTS `shorty`;

USE `shorty`;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INT AUTO_INCREMENT,
	external_id VARCHAR(36) NOT NULL UNIQUE,
	email VARCHAR(100) NOT NULL UNIQUE,
	password BLOB NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_login TIMESTAMP,
	account_enabled TINYINT NOT NULL DEFAULT FALSE,
	refresh_token TEXT,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS hosts;
CREATE TABLE hosts (
  id INT AUTO_INCREMENT,
	external_id VARCHAR(36) NOT NULL UNIQUE,
	full_url VARCHAR(255) NOT NULL,
	short_url varchar(25) NOT NULL UNIQUE,
	PRIMARY KEY (id),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS urls;
CREATE TABLE urls(
	id INT AUTO_INCREMENT,
	external_id VARCHAR(36) NOT NULL,
	source_url VARCHAR(255) NOT NULL,
	target_url VARCHAR(255) NOT NULL,
	active TINYINT NOT NULL DEFAULT TRUE,
	custom_url TINYINT NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	author_id INT NOT NULL,
	host_id INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY fk_author(author_id)
		REFERENCES users(id)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	FOREIGN KEY fk_host(host_id)
		REFERENCES hosts(id)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS browsers;
CREATE TABLE browsers (
	id INT NOT NULL AUTO_INCREMENT,
	external_id VARCHAR(36) NOT NULL,
	name VARCHAR(50),
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS oss;
CREATE TABLE oss (
	id INT NOT NULL AUTO_INCREMENT,
	external_id VARCHAR(36) NOT NULL,
	name VARCHAR(50),
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS device_type
CREATE TABLE device_type (
  id INT NOT NULL AUTO_INCREMENT,
  type varchar(20) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY id (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `device_type` (`type`) VALUES ('mobile'), ('tablet'), ('desktop'), ('other');

DROP TABLE IF EXISTS stats;
CREATE TABLE stats (
	id INT NOT NULL AUTO_INCREMENT,
	url_id INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	browser_id INT NOT NULL,
	os_id INT NOT NULL,
	device_id INT NOT NULL,
	referrer VARCHAR(255) NOT NULL,
	country VARCHAR(5) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY fk_url(url_id)
		REFERENCES urls(id)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	FOREIGN KEY fk_browser(browser_id)
		REFERENCES browsers(id)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	FOREIGN KEY fk_os(os_id)
		REFERENCES oss(id)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION
	FOREIGN KEY fk_device(device_id)
		REFERENCES device_type(id)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `keys`;
CREATE TABLE `keys` (
	id INT NOT NULL AUTO_INCREMENT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`issuer` VARCHAR(255) NOT NULL UNIQUE,
	`key` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
